map_type: costmap

obstacle_range: 1.0
raytrace_range: 3.0

transform_tolerance: 1.2

footprint: [[-0.15, 0.2], [0.15, 0.2], [0.15, -0.2], [-0.15, -0.2]]


robot_radius: 0.5 
inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
